name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11", "3.12"]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install uv
        uses: astral-sh/setup-uv@v3
        with:
          version: "latest"

      - name: Install dependencies (editable with dev extras)
        run: |
          uv pip install -U pip
          uv pip install -e '.[dev]'

      - name: Ruff
        run: uv run ruff check .

      - name: MyPy
        run: uv run mypy ynab_mcp_server

      - name: Pytest
        run: uv run pytest -q
